oGfxRot    equ 0x001A
oGfxRotX   equ 0x001A
oGfxRotY   equ 0x001C
oGfxRotZ   equ 0x001E
oGfxPos    equ 0x0020
oGfxPosX   equ 0x0020
oGfxPosY   equ 0x0024
oGfxPosZ   equ 0x0028
oGfxScale  equ 0x002C
oGfxScaleX equ 0x002C
oGfxScaleY equ 0x0030
oGfxScaleZ equ 0x0034

oParentObj equ 0x0068

oPos       equ 0x00A0
oPosX      equ 0x00A0
oPosY      equ 0x00A4
oPosZ      equ 0x00A8
oRot       equ 0x00D0
oRotX      equ 0x00D0
oRotY      equ 0x00D4
oRotZ      equ 0x00D8

oBhvParam2 equ 0x0144
oBhvParams equ 0x0188
